### ISSUE TITLE
builtins.KeyError

### ISSUE THREAD

**Issue by dwilkie1** [microsoftgraph/python-sample-send-mail#6]
Getting this error right after signing in. Same issue on chrome & IE 11. Tried incognito & private mode. Any ideas?

Traceback (most recent call last):
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\repos\python-sample-send-mail-master\sample.py", line 44, in authorized
    if str(flask.session['state']) != str(flask.request.args['state']):
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\werkzeug\local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "C:\Users\dwilkie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\sessions.py", line 83, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'state'

**Comment by flyerbirdy** [comment]
This is the answer 
In the Graph setting the Redirect URLs is "http://localhost:5000/login/authorized"  
if using the http://127.0.0.1 is wrong URLs. So It call URLs error

**Comment by dwilkie1** [comment]
Thanks for the response. Could you help me understand what the correct redirect URL should be?

**Comment by jasonjoh** [comment]
@dwilkie1 we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
